### ISSUE TITLE
compatibility for older versions of keycloak

### ISSUE THREAD

**Issue by raj-saroj-vst-au4** [itpropro/nuxt-oidc-auth#15]
On older versions of keycloak that are facing error: 500 Token request failed on browser 
&  ERROR  [nuxt-oidc-auth]: { error: 'RESTEASY003065: Cannot consume content type' } on console

Cause : improper request-form data generation & header content-type json

fix: 

1) use of URLSearchParams() class for request form generation instead of FormData() class
2) content-type to be explicity defined as "application/x-www-form-urlencoded" in the headers

**Comment by DallasHoff** [comment]
This is the purpose of #12

**Comment by raj-saroj-vst-au4** [comment]
https://github.com/itpropro/nuxt-oidc-auth/pull/12 was merged but its not reflected in npm ?

**Comment by raj-saroj-vst-au4** [comment]
after trying your commit, it works but its not able to refresh token on my version of keycloak ! 
 urlsearchparams() works for both accesstoken and refresh token, despite default tokenaccesstype as form.

**Comment by itpropro** [comment]
It's not published yet, because the current implementation breaks some other providers. 
Currently. the content-type is already `application/x-www-form-urlencoded` when using the form format based on the `FormData`, which is the standard defined by the fetch spec.
I will have to find a fix first to handle these special KeyCloak use cases without breaking the other providers, as explicitly defining content-type headers is not recommended and should be avoided if possible, which is why it breaks other providers.

**Comment by itpropro** [comment]
The library now relies on the inference of ofetch for the content-type, as nothing else is currently possible. The parameter `form-urlencoded` will hand over a `URLSearchParams` object and the `form` parameter a `FormData` object to ofetch.
