### ISSUE TITLE
Module / plugin not setting session

### ISSUE THREAD

**Issue by ekarlso** [itpropro/nuxt-oidc-auth#50]
Hi, what can be wrong if I am redirect back to my nuxt app and no session is set? I get no errors in logs or anything but it says I am not logged in.

If I enable global middleware I am eternally forwarded back and forth.

**Comment by itpropro** [comment]
Can you provide a reproduction or some console logs? Are you using Nuxt in SSR mode?

**Comment by ekarlso** [comment]
Ah yeah, that was it with SSR was turned off.

**Comment by VictorioBerra** [comment]
Is there a way to use this with SSR false? Cant the front-end read the cookie?

**Comment by itpropro** [comment]
> Is there a way to use this with SSR false? Cant the front-end read the cookie?

We are using auth code flow with confidential client scenario. That is not possible without a server side component, as you should never use a client secret in a client side application.
You can theoretically use OAuth flows from an SPA, but that is inheritly more insecure than having a server side component to authentication, which is why we or nuxt auth utils is not supporting it in the first place.
Is there any reason preventing you from using SSR?
